### ISSUE TITLE
make start gives error

### ISSUE THREAD

**Issue by hostingwalk** [cloudflare/flan#22]
```
make start
docker run --name flan_1574462973 -v /root/flan/shared:/shared flan_scan
mkdir: can't create directory '/shared/xml_files/2019.11.22-22.49': Permission denied
/run.sh: line 34: can't open /shared/ips.txt: Permission denied
Traceback (most recent call last):
  File "/output_report.py", line 227, in <module>
    main()
  File "/output_report.py", line 213, in main
    for i, filename in enumerate(os.listdir(dirname)):
FileNotFoundError: [Errno 2] No such file or directory: '/shared/xml_files/2019.11.22-22.49'
sed: /shared/reports/report_2019.11.22-22.49.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-22.49.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-22.49.tex: No such file or directory
sed: /shared/reports/report_2019.11.22-22.49.tex: No such file or directory
```

Make version:  GNU Make 3.82
Docker version:   1.13.1
OS:   CentOS   7.7

**Comment by hostingwalk** [comment]
issue #10  SELinux was enabled.
