### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by trip-nine** [cloudflare/flan#52]
I am getting a connection error when trying to scan a few test IPs.. it scans 1 correctly, then runs into errors on the final 2.. will the report not print into .tex unless all IPs are on??

Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Tue Feb 18 18:25:33 2020 -- 1 IP address (1 host up) scanned in 22.79 seconds
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1133, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1178, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1129, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 944, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 887, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1279, in connect
    super().connect()
  File "/usr/local/lib/python3.5/http/client.py", line 859, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/usr/local/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/output_report.py", line 238, in <module>
    main()
  File "/output_report.py", line 234, in main
    create_latex(nmap_command, start_date)
  File "/output_report.py", line 174, in create_latex
    + '\\\\ \hline \end{tabular}  '
  File "/output_report.py", line 132, in get_description
    cve_json = json.loads(urllib.urlopen(url).read().decode("utf-8"))
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>
sed: /shared/reports/report_2020.02.18-18.24.tex: No such file or directory
sed: /shared/reports/report_2020.02.18-18.24.tex: No such file or directory
sed: /shared/reports/report_2020.02.18-18.24.tex: No such file or directory
sed: /shared/reports/report_2020.02.18-18.24.tex: No such file or directory

**Comment by nadinelyab** [comment]
Hey @trip-nine,
Flan just went through a big refactor so I think this might be fixed. The issue you're posting seems to be that there was some error getting the description of a cve when generating the report. The whole process crashes since there was no error handling when getting the description. The refactor has this error checking so please try again.
