### ISSUE TITLE
Error generating report

### ISSUE THREAD

**Issue by jcmanjar** [cloudflare/flan#55]
After doing the network scan, the following error was generated:

```
Read data files from: /usr/bin/../share/nmap
Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
# Nmap done at Tue Mar 10 19:18:29 2020 -- 256 IP addresses (53 hosts up) scanned in 527.44 seconds
Traceback (most recent call last):
  File "/output_report.py", line 72, in <module>
    main(*sys.argv[1:4], report_type='latex')
  File "/output_report.py", line 68, in main
    create_report(parser, builder, nmap_command, start_date, output, ip_source)
  File "/output_report.py", line 20, in create_report
    builder.add_vulnerable_services(parser.vulnerable_dict)
  File "/contrib/report_builders/latex_report_builder.py", line 58, in add_vulnerable_services
    + '\\\\ \\hline \\end{tabular}  ')
AttributeError: 'str' object has no attribute 'url'

```

**Comment by nadinelyab** [comment]
Hi @jcmanjar,
I believe I just fixed that error earlier today. Can you pull the latest changes and try again?
Thanks!

**Comment by jcmanjar** [comment]
Hi, Nadine
I tried again and it worked just fine, thank you very much!!! and thanks for your fast response!
