### ISSUE TITLE
mkdir: can't create directory '/shared/xml_files/2022.02.24-09.54': Permission denied

### ISSUE THREAD

**Issue by NexGenTech** [cloudflare/flan#73]
I followed the instructions in the descripiton in order to clone and run it but I run into these errors :

```
docker run --rm --cap-drop=all --cap-add=NET_RAW --name flan_1645696455 -v "/home/lazarakis/Desktop/Code/flan/shared:/shared:Z" flan_scan
mkdir: can't create directory '/shared/xml_files/2022.02.24-09.54': Permission denied
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/1.1.1.1.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/1.1.1.1.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/8.8.8.8.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/8.8.8.8.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/127.0.0.0-8.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/127.0.0.0-8.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/192.168.1.235.xml for writing: No such file or directory (2)
Failed to open XML output file /shared/xml_files/2022.02.24-09.54/192.168.1.235.xml for writing: No such file or directory (2)
Traceback (most recent call last):
  File "/output_report.py", line 9, in <module>
    from contrib.report_builders import ReportBuilder, LatexReportBuilder, MarkdownReportBuilder, JinjaHtmlReportBuilder, \
  File "/contrib/report_builders/__init__.py", line 5, in <module>
    from .html_report_builder import JinjaHtmlReportBuilder
  File "/contrib/report_builders/html_report_builder.py", line 4, in <module>
    from jinja2 import Template, FileSystemLoader, Environment
  File "/usr/local/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.9/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.9/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/site-packages/markupsafe/__init__.py)
sed: /shared/reports/report_2022.02.24-09.54.tex: No such file or directory
sed: /shared/reports/report_2022.02.24-09.54.tex: No such file or directory
sed: /shared/reports/report_2022.02.24-09.54.tex: No such file or directory
sed: /shared/reports/report_2022.02.24-09.54.tex: No such file or directory
```

As I can see, the root of all problems is the first error : 
```
mkdir: can't create directory '/shared/xml_files/2022.02.24-09.54': Permission denied
```

**Comment by Rocket01666** [comment]
yup same issue for me 
mkdir: can't create directory '/shared/xml_files/2022.03.17-15.06': Permission denied

**Comment by mil2ne** [comment]
It's probably a markupsafe version issue.
ㄴ https://markupsafe.palletsprojects.com/en/2.1.x/changes/

Add the line below to requirements.txt and try start after make build.

MarkupSafe==2.0.1

**Comment by btv** [comment]
I was able to get this to work by setting the permissions of the `shared` directory to `777`.

**Comment by ngocdd** [comment]
Still got the same issue on Oct-2024, change chmod to 777 still not work
